### ISSUE TITLE
JRuby compatability issue

### ISSUE THREAD

**Issue by sharkos** [openshift/rhc#330]
When using 'rhc' to clone the repo using the JRuby VM, calling 'git' using fork fails.

ose]$  rhc git-clone firstphp
Password: ****
NotImplementedError: fork is not available on this platform
                   fork at org/jruby/RubyKernel.java:1766
               do_popen at /home/ctusa/dev/jruby-1.7.3/lib/ruby/gems/shared/gems/open4-1.3.0/lib/open4.rb:58
                 popen4 at /home/ctusa/dev/jruby-1.7.3/lib/ruby/gems/shared/gems/open4-1.3.0/lib/open4.rb:30
                  spawn at /home/ctusa/dev/jruby-1.7.3/lib/ruby/gems/shared/gems/open4-1.3.0/lib/open4.rb:331
                timeout at org/jruby/ext/timeout/Timeout.java:105
                  spawn at /home/ctusa/dev/jruby-1.7.3/lib/ruby/gems/shared/gems/open4-1.3.0/lib/open4.rb:330
                   call at org/jruby/RubyProc.java:249
                  chdir at /home/ctusa/dev/jruby-1.7.3/lib/ruby/gems/shared/gems/open4-1.3.0/lib/open4.rb:369
                  spawn at /home/ctusa/dev/jruby-1.7.3/lib/ruby/gems/shared/gems/open4-1.3.0/lib/open4.rb:329
           run_with_tee at /home/ctusa/dev/jruby-1.7.3/lib/ruby/gems/shared/gems/rhc-1.4.8/lib/rhc/helpers.rb:493
         git_clone_repo at /home/ctusa/dev/jruby-1.7.3/lib/ruby/gems/shared/gems/rhc-1.4.8/lib/rhc/git_helpers.rb:65
  git_clone_application at /home/ctusa/dev/jruby-1.7.3/lib/ruby/gems/shared/gems/rhc-1.4.8/lib/rhc/git_helpers.rb:23
                    run at /home/ctusa/dev/jruby-1.7.3/lib/ruby/gems/shared/gems/rhc-1.4.8/lib/rhc/commands/git_clone.rb:22
               __send__ at org/jruby/RubyBasicObject.java:1683
                   send at org/jruby/RubyKernel.java:2107
                execute at /home/ctusa/dev/jruby-1.7.3/lib/ruby/gems/shared/gems/rhc-1.4.8/lib/rhc/commands.rb:201
           to_commander at /home/ctusa/dev/jruby-1.7.3/lib/ruby/gems/shared/gems/rhc-1.4.8/lib/rhc/commands.rb:192
                   call at org/jruby/RubyProc.java:249
                   call at /home/ctusa/dev/jruby-1.7.3/lib/ruby/gems/shared/gems/commander-4.1.3/lib/commander/command.rb:180
                    run at /home/ctusa/dev/jruby-1.7.3/lib/ruby/gems/shared/gems/commander-4.1.3/lib/commander/command.rb:155
     run_active_command at /home/ctusa/dev/jruby-1.7.3/lib/ruby/gems/shared/gems/commander-4.1.3/lib/commander/runner.rb:402
                   run! at /home/ctusa/dev/jruby-1.7.3/lib/ruby/gems/shared/gems/rhc-1.4.8/lib/rhc/command_runner.rb:61
                   run! at /home/ctusa/dev/jruby-1.7.3/lib/ruby/gems/shared/gems/commander-4.1.3/lib/commander/delegates.rb:11
                  start at /home/ctusa/dev/jruby-1.7.3/lib/ruby/gems/shared/gems/rhc-1.4.8/lib/rhc/cli.rb:42
                 (root) at /home/ctusa/dev/jruby-1.7.3/lib/ruby/gems/shared/gems/rhc-1.4.8/bin/rhc:18
                   load at org/jruby/RubyKernel.java:1046
                 (root) at /home/ctusa/dev/jruby-1.7.3/bin/rhc:23

**Comment by tiwillia** [comment]
This was fixed with https://github.com/openshift/rhc/pull/580 in [BZ #1088960](https://bugzilla.redhat.com/show_bug.cgi?id=1088960) as mentioned above.

@danmcp this can be closed
