### ISSUE TITLE
gem install rhc failed. Gem::DependencyError

### ISSUE THREAD

**Issue by anton-haldin** [openshift/rhc#678]
Hi 
I'm using rhc command line in my deployment automation 

Today I've found that there is an issue with dependecies in gem

I'm trying to execute:
$gem install rhc
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: rhc requires highline (~> 1.6.11); commander requires highline (~> 1.7.1)

Please advise me who can help me with it.

Anton

**Comment by hermanos** [comment]
I have the same problem:
Unable to resolve dependencies: rhc requires highline (~> 1.6.11); commander requires highline (~> 1.7.1)

**Comment by hermanos** [comment]
The solution on a mac:
```
gem install rubygems-update
rbenv rehash # if you use rbenv
update_rubygems
gem install rhc
```

It works! :)

**Comment by anton-haldin** [comment]
Thank you very much hermanos
Looks like I was using old rebygems.

**Comment by vishivish18** [comment]
Any suggestion for windows? 
I have tried 'gem install rubygems-update'
Still getting the same error

**Comment by vishivish18** [comment]
Sorry guys I resolved it at my end in windows. 
Please igonre my previous comment and keep the status to closed itself
Thanks hermanos, your solution works.

**Comment by voidcode** [comment]
@hermanos solution work to on my Ubuntu 14.04 server.

```
sudo gem install rubygems-update
sudo update_rubygems
sudo gem install rhc
```

**Comment by chiragparekh** [comment]
Hi @vishivish18 I solved the same problem by running the following command before executing gem install rhc:

gem install highline -v 1.6.11

Hope this works !!

**Comment by icflorescu** [comment]
Same workaround appears to be working on Windows too.

**Comment by aichaoguy** [comment]
Thanks to @hermanos .
```
sudo gem install rubygems-update
sudo update_rubygems
sudo gem install rhc
```
Works on my Ubuntu 12.04 Desktop

**Comment by juanleal** [comment]
Thanks!!

**Comment by hilbix** [comment]
@hermanos thanks, your advice worked at my side, as I tried to follow https://developers.openshift.com/en/getting-started-debian-ubuntu.html#client-tools but this failed.

So on Ubuntu 14.04 Desktop following "oneliner" did the job (run as `root`):

`apt-get install ruby-full; gem install rubygems-update; update_rubygems; gem install rhc`

Note that `apt-get install rubygems` as noted in the doc does not work for Ubuntu 14.04.  Please also note that the "oneliner" outputs several dozend zillions lines of text, so I might have missed some quirks.  But `rhc setup` and `ssh ssh APP` worked afterwards as expected.

**Comment by piovezan** [comment]
The following command sequence is not working in Windows 7 Ultimate 64 bits:
````
install rubygems-update
update_rubygems
gem install rhc
```
The last command always results in the initial error message:
```
    ERROR:  While executing gem ... (Gem::DependencyError)
        Unable to resolve dependencies: rhc requires highline (~> 1.6.11); commander requires highline (~> 1.7.1)
```

**Comment by chamroeunbm** [comment]
It works on my Macs. thanks

**Comment by arnyepstein** [comment]
Unfortunately not for me ... I followed the procedure and could install, but not run.  I get this error:

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1206:in `block in activate_dependencies': can't satisfy 'highline (~> 1.6.11)', already activated 'highline-1.7.1' (Gem::LoadError)

Here is what I have installed:
gem  list

*** LOCAL GEMS ***

archive-tar-minitar (0.5.2)
bigdecimal (1.2.7, 1.2.0)
CFPropertyList (2.3.1, 2.2.0)
commander (4.3.2)
highline (1.7.1, 1.6.11)
httpclient (2.6.0.1)
io-console (0.4.2)
json (1.8.2, 1.7.7)
libxml-ruby (2.8.0, 2.6.0)
mini_portile (0.6.2)
minitest (5.5.1, 4.3.2)
net-scp (1.2.1)
net-ssh (2.9.2)
net-ssh-gateway (1.2.0)
net-ssh-multi (1.2.0)
nokogiri (1.6.6.2, 1.5.6)
open4 (1.3.4)
power_assert (0.2.3)
psych (2.0.13, 2.0.0)
rake (10.4.2, 0.9.6)
rdoc (4.2.0, 4.0.0)
rhc (1.35.1)
rubygems-update (2.4.6)
sqlite3 (1.3.10, 1.3.7)
test-unit (3.0.9, 2.0.0.0)

**Comment by hermanos** [comment]
Did you run update_rubygems?

Off-topic: I see you are using the system ruby, did you try to manage your
rubies using rbenv or rvm?

________________________
Mircea Gherman

"Too much agreement kills a chat."

**Comment by arnyepstein** [comment]
I did run update_rubygems ... it said nothing to update.
I am using system ruby.

**Comment by arnyepstein** [comment]
OK, I got it to work by =:
- Installing rbenv
- Running the following again:

rbenv rehash
update_rubygems
gem install rhc

**Comment by selahattinunlu** [comment]
@hermanos Thanks :)

**Comment by hermanos** [comment]
Welcome, it was just an update, glad I could help though :)

________________________
Mircea Gherman

"Too much agreement kills a chat."

**Comment by arnyepstein** [comment]
@hermanos Thanks for your help.

**Comment by kyubix** [comment]
@piovezan try add gem before install, it's should be like this

gem install rubygems-update
update_rubygems
gem install rhc

**Comment by japcoding** [comment]
i found a solution on EI Capitan

On El Capitan you need to change where ruby installs gems using vim ~/.gemrc and adding gem: -n/usr/local/bin.
