### ISSUE TITLE
Error Gem Install RHC

### ISSUE THREAD

**Issue by rhonyabdullah** [openshift/rhc#680]
Following this [Steps](https://developers.openshift.com/en/getting-started-debian-ubuntu.html#client-tools) to install the "Client Tools", when execute this command:

>gem install rhc

Give me error like this:
> ERROR:  While executing gem ... (NoMethodError)
    undefined method `include?' for nil:NilClass

I'm running on Linux Mint 13

**Comment by axilleas** [comment]
Did you use `sudo`?

```
sudo gem install rhc
```
