### ISSUE TITLE
Error recognizing git on windows

### ISSUE THREAD

**Issue by jaschweder** [openshift/rhc#689]
I have installed rhc in windows 8.1, when I try to execute "rhc git-clone application" it's say that git client is not installed, but I have git installed on my machine has you can see in this screenshot
![erro_rhc_git_client](https://cloud.githubusercontent.com/assets/6409113/7778617/6fe367ce-00a3-11e5-8a70-083c95aace6d.png)

**Comment by foustleague** [comment]
You are using GIT Bash?

Just try it:

![sem titulo-3](https://cloud.githubusercontent.com/assets/13892727/9447762/728b929c-4a6f-11e5-9732-4f117b256457.jpg)

After

![sem titulo-4](https://cloud.githubusercontent.com/assets/13892727/9447820/b29c29a0-4a6f-11e5-8e5b-bf2ade4a69a3.jpg)

**Comment by jaschweder** [comment]
Success! that's works to me
