### ISSUE TITLE
autocompletion for zsh

### ISSUE THREAD

**Issue by aiguofer** [openshift/rhc#697]
Hey, I'm currently using autocompletion in zsh using `bashcompinit`, but it errors out with `_rhc:14: unrecognized modifier 'C'` when I put in more than 1 command.

Are there any plans to improve completion in zsh?

Thanks!

**Comment by blueyed** [comment]
Fixed/addressed by https://github.com/openshift/rhc/pull/729.

**Comment by blueyed** [comment]
Apart from that, it would be nice to have proper completion for Zsh (without using the bash wrapper), and if the completion would be more enhanced, e.g. completing apps.

**Comment by aiguofer** [comment]
Tried that locally, seems to work for me! :+1: 

And I totally agree, better completion (like completing apps and servers) would be awesome. I thought that there had been a request for that before, but I can't seem to find it.
