### ISSUE TITLE
 Error installing rhc:         net-ssh requires Ruby version >= 2.0.

### ISSUE THREAD

**Issue by vkhv** [openshift/rhc#763]
Hi everone,  trying to install rhc.
```
pi@raspberrypi:~ $ sudo gem install rhc
ERROR:  Error installing rhc:
        net-ssh requires Ruby version >= 2.0.
pi@raspberrypi:~ $ ruby -v
ruby 2.1.5p273 (2014-11-13) [arm-linux-gnueabihf]
```

Why i got this error? I used version higer then 2.

**Comment by vkhv** [comment]
solved problem:
```
 sudo gem install net-ssh -v 2.9.2
```

**Comment by klifvegeta** [comment]
thanks very much

**Comment by siripuramrk** [comment]
thnku @vkhv

**Comment by BillRizer** [comment]
thanks

**Comment by infotek** [comment]
using:
Ubuntu 14.04.5 LTS, Trusty Tahr
error when running "gem install" results in...

net-ssh requires Ruby version >= 2.0

fix:

apt install ruby2.0 ruby2.0-dev rubygems-integration

ln -fs /usr/bin/erb2.0 /usr/bin/erb
ln -fs /usr/bin/irb2.0 /usr/bin/irb
ln -fs /usr/bin/rdoc2.0 /usr/bin/rdoc
ln -fs /usr/bin/ri2.0 /usr/bin/ri
ln -fs /usr/bin/ruby2.0 /usr/bin/ruby
ln -fs /usr/bin/testrb2.0 /usr/bin/testrb
ln -fs /usr/bin/gem2.0 /usr/bin/gem

rerun "gem install"

**Comment by engkarim** [comment]
thanks man @infotek
